[workspace]
members = ["crates/ic10-core", "crates/ic10-data", "crates/ic10-lsp"]
resolver = "2"

[workspace.package]
version = "0.1.2"
edition = "2024"
rust-version = "1.90"
repository = "https://github.com/ShaneYu/stationeers-vscode-extension"
license = "MIT"

[workspace.dependencies]
ic10-core = { path = "crates/ic10-core" }
ic10-data = { path = "crates/ic10-data" }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = [
  "io-std",
  "macros",
  "rt-multi-thread",
  "sync",
] }
tower-lsp = "0.20.0"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
