import * as vscode from "vscode";
import { BridgeChip, BridgeClient, BridgeScope, BridgeSnapshot, BridgeState } from "./bridge";
import { getLiveChipContext } from "./liveExplorerModel";

export const LIVE_CONTEXT = { connected: "stationeers.bridge.connected", read: "stationeers.bridge.canReadIc10", write: "stationeers.bridge.canWriteIc10", language: "stationeers.liveChip.language", stale: "stationeers.liveChip.stale", available: "stationeers.liveChip.available", canRead: "stationeers.liveChip.canRead", canCompare: "stationeers.liveChip.canCompare", luaDebugEligible: "stationeers.liveChip.luaDebugEligible", lua: "stationeers.stationeersLua.connected" } as const;

type Node = StatusNode | ScopeNode | ChipNode | WarningNode;
class StatusNode extends vscode.TreeItem { readonly nodeKind = "status"; constructor(label: string, contextValue = "bridgeStatus") { super(label, vscode.TreeItemCollapsibleState.None); this.contextValue = contextValue; this.iconPath = new vscode.ThemeIcon("plug"); } }
class ScopeNode extends vscode.TreeItem { readonly nodeKind = "scope"; constructor(readonly scope: BridgeScope) { super(scope.disambiguator ? `${scope.name} · ${scope.disambiguator}` : scope.name, vscode.TreeItemCollapsibleState.Collapsed); this.id = `scope:${scope.scopeId}`; this.contextValue = "liveScope"; this.description = `${scope.anchorCount} anchor${scope.anchorCount === 1 ? "" : "s"}`; this.iconPath = new vscode.ThemeIcon("broadcast"); } }
export class ChipNode extends vscode.TreeItem { readonly nodeKind = "chip"; constructor(readonly chip: BridgeChip, readonly scopeId: string, readonly stale: boolean) { super(chip.housingName, vscode.TreeItemCollapsibleState.None); this.id = `chip:${scopeId}:${chip.chipId}`; this.description = `${chip.language.toUpperCase()} · ${chip.powered ? "powered" : "unpowered"}`; this.tooltip = `${chip.housingName}\n${chip.housingPrefab}\nReference ${chip.housingReferenceId}`; this.contextValue = chip.language === "ic10" ? "liveIc10Chip" : "liveLuaChip"; this.iconPath = new vscode.ThemeIcon(chip.powered ? "circuit-board" : "circle-slash"); }
}
class WarningNode extends vscode.TreeItem { readonly nodeKind = "warning"; constructor(readonly warning: { message: string; anchorReferenceId?: string }) { super(warning.message, vscode.TreeItemCollapsibleState.None); this.contextValue = "bridgeWarning"; this.iconPath = new vscode.ThemeIcon("warning"); } }

export class LiveNetworkTree implements vscode.TreeDataProvider<Node>, vscode.Disposable {
  private readonly changed = new vscode.EventEmitter<Node | undefined | null | void>(); private snapshot?: BridgeSnapshot; private state: BridgeState = "disabled";
  readonly onDidChangeTreeData = this.changed.event;
  constructor(readonly client: BridgeClient) { client.onDidChangeState((state) => { this.state = state; this.snapshot = client.snapshot; this.changed.fire(); }); }
  setSnapshot(snapshot: BridgeSnapshot): void { this.snapshot = snapshot; this.changed.fire(); }
  getTreeItem(element: Node): vscode.TreeItem { return element; }
  getChildren(element?: Node): Node[] {
    if (!element) { if (this.state === "disabled") return [new StatusNode("Bridge disconnected", "bridgeDisconnected")]; if (this.state !== "connected") return [new StatusNode(`Bridge ${this.state}`, "bridgeStatus")]; return [new StatusNode(`Connected · world ${this.snapshot?.revision ?? "?"}`), ...(this.snapshot?.scopes ?? []).slice().sort(scopeSort).map((scope) => new ScopeNode(scope)), ...((this.snapshot?.warnings.length ?? 0) > 0 ? [new StatusNode("Configuration warnings", "bridgeWarnings")] : [])]; }
    if (element instanceof ScopeNode) { const chips = this.snapshot?.chips ?? []; return element.scope.chipIds.map((id) => chips.find((chip) => chip.chipId === id)).filter((chip): chip is BridgeChip => Boolean(chip)).sort(chipSort).map((chip) => new ChipNode(chip, element.scope.scopeId, this.state !== "connected")); }
    if (element.contextValue === "bridgeWarnings") return (this.snapshot?.warnings ?? []).map((warning) => new WarningNode(warning));
    return [];
  }
  dispose(): void { this.changed.dispose(); }
}

export class LiveExplorer implements vscode.Disposable {
  private readonly tree: LiveNetworkTree; private readonly view: vscode.TreeView<Node>; private readonly status: vscode.StatusBarItem; private readonly disposables: vscode.Disposable[] = [];
  private selectedChip?: ChipNode; private lastState: BridgeState = "disabled"; private outageNotified = false; private autoConnectInFlight = false; private refreshInFlight = false;
  constructor(private readonly context: vscode.ExtensionContext, private readonly client: BridgeClient) {
    this.tree = new LiveNetworkTree(client); this.view = vscode.window.createTreeView("stationeers.liveNetworks", { treeDataProvider: this.tree, showCollapseAll: true, canSelectMany: false, dragAndDropController: new LiveDropController(client, this.tree) });
    this.status = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 80); this.status.command = "stationeers.live.connect"; this.status.show();
    this.disposables.push(this.tree, this.view, this.status, client.onDidChangeState((state) => { if (this.lastState === "connected" && state !== "connected" && !this.outageNotified) { this.outageNotified = true; void vscode.window.showWarningMessage("Stationeers bridge connection lost. Start the game to reconnect."); } if (state === "connected") { this.outageNotified = false; } this.lastState = state; void this.updateContext(state); }), this.view.onDidChangeSelection((event) => { this.selectedChip = event.selection.find((item): item is ChipNode => item instanceof ChipNode); void this.updateSelectedContext(); }), vscode.workspace.onDidChangeConfiguration((event) => { if (event.affectsConfiguration("stationeers.bridge.url")) void this.reconnect(); }), { dispose: () => clearInterval(this.pollTimer) });
    this.pollTimer = setInterval(() => void this.poll(), 3000);
    void this.updateContext(client.state);
  }
  private readonly pollTimer: ReturnType<typeof setInterval>;
  async connect(): Promise<void> { if (vscode.env.remoteName) { void vscode.window.showWarningMessage("Live Stationeers discovery is local-only. Use a local VS Code window or explicitly forward the bridge port; this extension will not contact a remote machine."); return; } try { let token = await this.context.secrets.get("stationeers.bridge.token"); if (!token) { token = await this.client.pair(); await this.context.secrets.store("stationeers.bridge.token", token); } this.client.setEndpoint(this.bridgeUrl(), token); await this.client.connect(); void vscode.window.showInformationMessage("Connected to the Stationeers bridge."); } catch (error) { void vscode.window.showErrorMessage(`Stationeers bridge: ${error instanceof Error ? error.message : String(error)}`); } }
  async autoConnect(): Promise<void> { if (vscode.env.remoteName || this.autoConnectInFlight || this.client.state === "connected" || this.client.state === "discovering" || this.client.state === "pairing") return; this.autoConnectInFlight = true; try { const token = await this.context.secrets.get("stationeers.bridge.token") ?? await this.client.pair(); await this.context.secrets.store("stationeers.bridge.token", token); this.client.setEndpoint(this.bridgeUrl(), token); await this.client.connect(); } catch { /* The game may simply not be running yet. */ } finally { this.autoConnectInFlight = false; } }
  async pair(): Promise<void> { try { const token = await this.client.pair(); await this.context.secrets.store("stationeers.bridge.token", token); await this.reconnect(); } catch { const token = await vscode.window.showInputBox({ prompt: "Paste the Stationeers bridge pairing token (automatic pairing was unavailable)", password: true, ignoreFocusOut: true }); if (!token?.trim()) return; await this.context.secrets.store("stationeers.bridge.token", token.trim()); await this.reconnect(); } }
  async refresh(): Promise<void> { try { this.tree.setSnapshot(await this.client.refresh()); } catch (error) { void vscode.window.showErrorMessage(`Could not refresh live networks: ${error instanceof Error ? error.message : String(error)}`); } }
  async disconnect(): Promise<void> { this.client.disconnect(); }
  async pull(node: ChipNode): Promise<void> { if (node.chip.language !== "ic10") { void vscode.window.showInformationMessage("The bridge only exposes IC10 source; Lua source belongs to StationeersLua."); return; } try { const source = await this.client.source(node.chip); const uri = await vscode.window.showSaveDialog({ filters: { IC10: ["ic10"] }, saveLabel: "Pull IC10 source", defaultUri: vscode.Uri.joinPath(vscode.workspace.workspaceFolders?.[0]?.uri ?? vscode.Uri.file(""), `${node.chip.housingName.replace(/[^\w.-]+/g, "_")}.ic10`) }); if (!uri) return; await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(source.source)); await vscode.window.showTextDocument(uri); } catch (error) { void vscode.window.showErrorMessage(`Could not pull IC10 source: ${error instanceof Error ? error.message : String(error)}`); } }
  async compare(node: ChipNode, uri?: vscode.Uri): Promise<void> { try { const source = await this.client.source(node.chip); const local = uri ?? vscode.window.activeTextEditor?.document.uri; if (!local) { void vscode.window.showInformationMessage("Open or select an IC10 file to compare."); return; } const remote = await vscode.workspace.openTextDocument({ language: node.chip.language, content: source.source }); await vscode.commands.executeCommand("vscode.diff", local, remote.uri, `${node.chip.housingName} · bridge compare`); } catch (error) { void vscode.window.showErrorMessage(`Could not compare source: ${error instanceof Error ? error.message : String(error)}`); } }
  async copyReference(node: ChipNode): Promise<void> { await vscode.env.clipboard.writeText(node.chip.housingReferenceId); void vscode.window.showInformationMessage(`Copied housing reference ${node.chip.housingReferenceId}.`); }
  async search(): Promise<void> { const snapshot = this.client.snapshot; if (!snapshot) return; const items = snapshot.scopes.flatMap((scope) => scope.chipIds.map((id) => ({ scope, chip: snapshot.chips.find((chip) => chip.chipId === id) }))).filter((item): item is { scope: BridgeScope; chip: BridgeChip } => Boolean(item.chip)); const pick = await vscode.window.showQuickPick(items.map((item) => ({ label: item.chip.housingName, description: `${item.scope.name} · ${item.chip.language} · ${item.chip.housingReferenceId}`, detail: item.chip.housingPrefab, item })), { matchOnDescription: true, matchOnDetail: true, placeHolder: "Search live scopes, chips, prefabs, languages, and references" }); if (pick) { await this.view.reveal(new ChipNode(pick.item.chip, pick.item.scope.scopeId, false), { select: true, focus: true, expand: false }); } }
  dispose(): void { this.disposables.forEach((item) => item.dispose()); }
  private async poll(): Promise<void> { if (vscode.env.remoteName || this.refreshInFlight) return; if (this.client.state === "connected") { this.refreshInFlight = true; try { this.tree.setSnapshot(await this.client.refresh()); } catch { /* State and snapshot are updated by BridgeClient. */ } finally { this.refreshInFlight = false; } } else { await this.autoConnect(); } }
  private bridgeUrl(): string { return vscode.workspace.getConfiguration("stationeers.bridge").get<string>("url", "http://127.0.0.1:3032"); }
  private async reconnect(): Promise<void> { const token = await this.context.secrets.get("stationeers.bridge.token") ?? ""; try { this.client.setEndpoint(this.bridgeUrl(), token); } catch (error) { void vscode.window.showErrorMessage(String(error)); return; } await this.connect(); }
  private async updateContext(state: BridgeState): Promise<void> { const hello = this.client.hello; await Promise.all([vscode.commands.executeCommand("setContext", LIVE_CONTEXT.connected, state === "connected"), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.read, state === "connected" && Boolean(hello?.capabilities.ic10SourceRead)), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.write, state === "connected" && Boolean(hello?.capabilities.ic10SourceWrite)), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.lua, Boolean(hello?.mods?.stationeersLua?.detected)), this.updateSelectedContext()]); this.status.text = `$(broadcast) Bridge: ${state}`; this.status.tooltip = "Stationeers live network bridge"; }
  private async updateSelectedContext(): Promise<void> { const selected = this.selectedChip ? getLiveChipContext(this.selectedChip.chip, this.client.state, this.client.hello) : undefined; await Promise.all([vscode.commands.executeCommand("setContext", LIVE_CONTEXT.language, selected?.language ?? ""), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.stale, selected?.stale ?? false), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.available, selected?.available ?? false), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.canRead, selected?.canRead ?? false), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.canCompare, selected?.canCompare ?? false), vscode.commands.executeCommand("setContext", LIVE_CONTEXT.luaDebugEligible, selected?.luaDebugEligible ?? false)]); }
}

class LiveDropController implements vscode.TreeDragAndDropController<ChipNode> {
  readonly dropMimeTypes = ["text/uri-list", "files"]; readonly dragMimeTypes = ["text/uri-list"];
  constructor(private readonly client: BridgeClient, private readonly tree: LiveNetworkTree) {}
  async handleDrop(target: ChipNode | undefined, dataTransfer: vscode.DataTransfer): Promise<void> { if (!target) return; const item = dataTransfer.get("text/uri-list") ?? dataTransfer.get("files"); const value = await item?.asString(); const uri = value?.split(/\r?\n/).find((line) => line && !line.startsWith("#")); if (!uri) { void vscode.window.showWarningMessage("Drop an IC10 or Lua file onto a live chip."); return; } let file: vscode.Uri; try { file = vscode.Uri.parse(uri); } catch { void vscode.window.showWarningMessage("The dropped item is not a valid VS Code URI."); return; } const document = await vscode.workspace.openTextDocument(file); const compatible = (target.chip.language === "ic10" && document.languageId === "ic10") || (target.chip.language === "lua" && document.languageId === "lua"); if (!compatible) { void vscode.window.showWarningMessage(`This ${document.languageId} file is not compatible with the ${target.chip.language} chip.`); return; } if (target.chip.language !== "ic10") { void vscode.window.showInformationMessage("Lua deployment requires StationeersLua and is not part of this bridge item."); return; } await vscode.window.showInformationMessage("Drop preflight passed. Source was not changed; deployment requires P3.06.", "Compare").then((choice) => { if (choice) void vscode.commands.executeCommand("stationeers.live.compare", target, file); }); }
}

function scopeSort(a: BridgeScope, b: BridgeScope): number { return a.name.localeCompare(b.name) || (a.disambiguator ?? "").localeCompare(b.disambiguator ?? "") || a.scopeId.localeCompare(b.scopeId); }
function chipSort(a: BridgeChip, b: BridgeChip): number { return a.housingName.localeCompare(b.housingName) || a.housingReferenceId.localeCompare(b.housingReferenceId); }

export function registerLiveExplorer(context: vscode.ExtensionContext): LiveExplorer {
  const url = vscode.workspace.getConfiguration("stationeers.bridge").get<string>("url", "http://127.0.0.1:3032"); const token = "";
  const client = new BridgeClient(url, token); const explorer = new LiveExplorer(context, client); context.subscriptions.push(client, explorer); void explorer.autoConnect();
  context.subscriptions.push(vscode.commands.registerCommand("stationeers.live.connect", () => explorer.connect()), vscode.commands.registerCommand("stationeers.live.pair", () => explorer.pair()), vscode.commands.registerCommand("stationeers.live.refresh", () => explorer.refresh()), vscode.commands.registerCommand("stationeers.live.disconnect", () => explorer.disconnect()), vscode.commands.registerCommand("stationeers.live.search", () => explorer.search()), vscode.commands.registerCommand("stationeers.live.pull", (node: ChipNode) => explorer.pull(node)), vscode.commands.registerCommand("stationeers.live.compare", (node: ChipNode, uri?: vscode.Uri) => explorer.compare(node, uri)), vscode.commands.registerCommand("stationeers.live.copyReference", (node: ChipNode) => explorer.copyReference(node)));
  return explorer;
}
