import assert from "node:assert/strict";
import { test } from "node:test";
import { StationeersLuaClient, StationeersLuaError } from "./stationeersLua.ts";

function response(status: number, body: unknown, contentType = "application/json"): Response { return new Response(typeof body === "string" ? body : JSON.stringify(body), { status, headers: { "content-type": contentType } }); }
function transport(queue: Response[]): { fetch: (input: string, init: RequestInit) => Promise<Response>; calls: Array<{ input: string; init: RequestInit }> } { const calls: Array<{ input: string; init: RequestInit }> = []; return { calls, fetch: async (input, init) => { calls.push({ input, init }); const next = queue.shift(); if (!next) throw new Error("unexpected request"); return next; } }; }
const status = { name: "StationeersLua", status: "ok", version: "0.9.5.0", debugger_enabled: true };
const editor = { editor_open: false, allow_network_chip_access: true, allow_network_chip_access_only_for_wireless_boards: true, wireless_remote_access_only: true, selected_chip_ref_id: null, selected_housing_ref_id: null, selected_housing_name: null, network_id: 1607, network_ids: [1607], network_names: { "1607": "Network 1" }, accessible_chip_count: 1, selected_chip_debugger_available: false, selected_chip_debugger_reason: "No chip is currently selected." };
const chip = { ref_id: 882, housing_ref_id: 888, is_lua: true, is_library: false, has_error: false, is_selected: false, source_length: 10, source_version: 1, housing_name: "Ticker", housing_type: "CircuitHousing", network_id: 1607, is_on: true, modules: [], loaded_libraries: [] };
const source = { ref_id: 882, source: "print(1) ", is_lua: true, is_library: false };
function write(mode: "chip" | "editor_then_chip") { return { success: true, ref_id: 882, mode, editor_synced: mode === "editor_then_chip", editor_sync_path: mode === "chip" ? "not_attempted" : "selected_editor", editor_sync_reason: "", source_version: 2 }; }

test("gets status, editor, and chips with normalized IDs", async () => { const t = transport([response(200, status), response(200, editor), response(200, [chip])]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); assert.equal((await client.status()).version, "0.9.5.0"); assert.equal((await client.editor()).networkId, "1607"); const chips = await client.chips(); assert.equal(chips[0]?.refId, "882"); assert.equal(client.isAccessible(882), true); assert.equal(client.state, "available"); });
test("fails visibly for an unvalidated StationeersLua version", async () => { const t = transport([response(200, { ...status, version: "0.9.6.0" })]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); await assert.rejects(client.status(), (error: StationeersLuaError) => error.code === "incompatible" && error.status === 426); assert.equal(client.state, "incompatible"); });
test("marks a transport failure unavailable", async () => { const client = new StationeersLuaClient("http://127.0.0.1:3030", { fetch: async () => { throw new Error("connection refused"); } }); await assert.rejects(client.status(), (error: StationeersLuaError) => error.code === "transport"); assert.equal(client.state, "unavailable"); });
test("accepts the observed sparse no-scope editor response", async () => { const t = transport([response(200, { editor_open: false, allow_network_chip_access: true, allow_network_chip_access_only_for_wireless_boards: true, mcp_debug_tools_available: true, mcp_debug_tools_reason: "" })]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); const result = await client.editor(); assert.equal(result.wirelessRemoteAccessOnly, false); assert.deepEqual(result.networkIds, []); assert.equal(client.state, "no-scope"); });
test("maps a 400 no-scope response explicitly", async () => { const t = transport([response(400, { error: "no IC editor open" })]); const client = new StationeersLuaClient("http://localhost:3030", t); await assert.rejects(client.chips(), (error: StationeersLuaError) => error.code === "no_scope" && error.noScope && error.status === 400); assert.equal(client.state, "no-scope"); });
test("rejects malformed responses and invalid IDs", async () => { const t = transport([response(200, { bad: true })]); const client = new StationeersLuaClient("http://[::1]:3030", t); await assert.rejects(client.status(), (error: StationeersLuaError) => error.code === "malformed_response"); await assert.rejects(client.pull({ refId: Number.MAX_SAFE_INTEGER + 1, housingRefId: 888 }), (error: StationeersLuaError) => error.code === "invalid_ref_id"); });
test("pulls JSON-wrapped Lua source using the observed chip route", async () => { const t = transport([response(200, [chip]), response(200, source)]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); assert.equal(await client.pull({ refId: "882", housingRefId: "888" }), "print(1) "); assert.equal(t.calls[1]?.input, "http://127.0.0.1:3030/api/chips/882/code?mode=chip"); });
test("uses editor_then_chip only for an exact chip and housing selection", async () => { const selectedEditor = { ...editor, editor_open: true, wireless_remote_access_only: false, selected_chip_ref_id: 882, selected_housing_ref_id: 888, selected_housing_name: "Ticker" }; const t = transport([response(200, selectedEditor), response(200, write("editor_then_chip"))]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); await client.editor(); const result = await client.push({ refId: 882, housingRefId: 888 }, "print(2)"); assert.match(t.calls[1]?.input ?? "", /mode=editor_then_chip$/); assert.equal(result.sourceVersion, "2"); assert.equal(result.editorSynced, true); });
test("does not use editor_then_chip for stale selected IDs when the editor is closed", async () => { const closedEditor = { ...editor, editor_open: false, wireless_remote_access_only: true, selected_chip_ref_id: 882, selected_housing_ref_id: 888, selected_housing_name: "Ticker" }; const t = transport([response(200, closedEditor), response(200, [chip]), response(200, write("chip"))]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); await client.editor(); await client.chips(); await client.push({ refId: 882, housingRefId: 888 }, "print(2)"); assert.match(t.calls[2]?.input ?? "", /mode=chip$/); });
test("uses chip mode for another accessible chip when a different editor chip is open", async () => { const selectedEditor = { ...editor, editor_open: true, wireless_remote_access_only: false, selected_chip_ref_id: 1702, selected_housing_ref_id: 1626, selected_housing_name: "Other" }; const t = transport([response(200, selectedEditor), response(200, [chip]), response(200, write("chip"))]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); await client.editor(); await client.chips(); await client.push({ refId: 882, housingRefId: 888 }, "print(2)"); assert.match(t.calls[2]?.input ?? "", /mode=chip$/); });
test("uses chip mode for a wireless-only accessible target", async () => { const t = transport([response(200, editor), response(200, [chip]), response(200, write("chip"))]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); await client.editor(); await client.chips(); const result = await client.push({ refId: 882, housingRefId: 888 }, "print(2)"); assert.match(t.calls[2]?.input ?? "", /mode=chip$/); assert.equal(result.editorSynced, false); });
test("fails closed when the housing identity does not match", async () => { const t = transport([response(200, editor), response(200, [chip])]); const client = new StationeersLuaClient("http://127.0.0.1:3030", t); await client.editor(); await client.chips(); await assert.rejects(client.push({ refId: 882, housingRefId: 999 }, "print(2)"), (error: StationeersLuaError) => error.code === "inaccessible"); assert.equal(t.calls.length, 2); });
test("rejects a mismatched source identity", async () => { const client = new StationeersLuaClient("http://127.0.0.1:3030", transport([response(200, [chip]), response(200, { ...source, ref_id: 999 })])); await assert.rejects(client.pull({ refId: 882, housingRefId: 888 }), (error: StationeersLuaError) => error.code === "malformed_response"); });
test("propagates pull and push HTTP errors", async () => { const pull = new StationeersLuaClient("http://127.0.0.1:3030", transport([response(200, [chip]), response(404, "Not Found", "text/plain")])); await assert.rejects(pull.pull({ refId: 882, housingRefId: 888 }), (error: StationeersLuaError) => error.status === 404 && error.code === "http_error"); const pushTransport = transport([response(200, editor), response(200, [chip]), response(409, { error: "conflict" })]); const push = new StationeersLuaClient("http://127.0.0.1:3030", pushTransport); await assert.rejects(push.push({ refId: 882, housingRefId: 888 }, "print(3)"), (error: StationeersLuaError) => error.status === 409 && error.message === "conflict"); });
